### ISSUE TITLE
[Suggestion] Skip all type of segments

### ISSUE THREAD

**Issue by mbongenaar** [willemstuursma/castblock-php#1]
Hello Willem,

Is it possible to have it skip all types of segments, not only Sponsors?

Tool works really great by the way.

**Comment by willemstuursma** [comment]
Thanks @mbongenaar. I plan to make this configurable via an environment variable in the future.

**Comment by willemstuursma** [comment]
Resolved in [v0.2](https://github.com/willemstuursma/castblock-php/releases/tag/v0.2).
