### ISSUE TITLE
Failed retrieving identifier from go-chromecast output: YouTube (PLAYING), title=

### ISSUE THREAD

**Issue by NGPriest** [willemstuursma/castblock-php#5]
New install, getting the above/below error:

>php castblock-php.phar
>In Status.php line 37:
>  Failed retrieving identifier from go-chromecast output: YouTube (PLAYING), title="<deleted>", artist="<deleted>", time remaining=xxxs/xxxs, volume=0.14, muted=false
>app:run [-c|--category CATEGORY]`

`php castblock-php.phar -vvv
Box Requirements Checker
> Using PHP 7.4.3
> PHP is using the following php.ini file:
  /etc/php/7.4/cli/php.ini
> Checking Box requirements:
  ✔ The application requires the version "^7.1 || ^8.0" or greater.
  ✔ The application requires the extension "zlib".
  ✔ The application requires the extension "json".
  ✔ The package "guzzlehttp/guzzle" requires the extension "json".
  ✔ The package "myclabs/php-enum" requires the extension "json".
 [OK] Your system is ready to run the application.
[debug] Starting CastBlock PHP...
[info] Checking for new Chromecasts in local network...
[info] Found Chromecast "<deleted>" at <deleted>:8009.
[debug] Chromecast <deleted> is not playing Youtube.
[info] Found Google Home Mini "<deleted>" at <deleted>:8009.
[debug] Google Home Mini <deleted> is not playing Youtube.
[info] Found <deleted> "<deleted>" at <deleted>:8009.
In Status.php line 37:
  [WillemStuursma\CastBlock\Exception]
  Failed retrieving identifier from go-chromecast output: YouTube (PLAYING), title="<deleted>", artist="<deleted>", time remaining=xxxs/xxxs, volume=0.14, muted=false
Exception trace:
  at phar:///home/xxxxxxxx/castblock-php.phar/src/ValueObjects/Status.php:37
 WillemStuursma\CastBlock\ValueObjects\Status::fromGoChromeCastOutput() at phar:///home/xxxxxxxx/castblock-php.phar/src/ChromeCastConnector.php:61
 WillemStuursma\CastBlock\ChromeCastConnector->getStatus() at phar:///home/xxxxxxxx/castblock-php.phar/src/Commands/RunCommand.php:124
 WillemStuursma\CastBlock\Commands\RunCommand->skipSponsors() at phar:///home/xxxxxxxx/castblock-php.phar/src/Commands/RunCommand.php:107
 WillemStuursma\CastBlock\Commands\RunCommand->execute() at phar:///home/xxxxxxxx/castblock-php.phar/vendor/symfony/console/Command/Command.php:299
 Symfony\Component\Console\Command\Command->run() at phar:///home/xxxxxxxx/castblock-php.phar/vendor/symfony/console/Application.php:978
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/xxxxxxxx/castblock-php.phar/vendor/symfony/console/Application.php:295
 Symfony\Component\Console\Application->doRun() at phar:///home/xxxxxxxx/castblock-php.phar/vendor/symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at phar:///home/xxxxxxxx/castblock-php.phar/bin/castblock-php:14
 require() at /home/xxxxxxxx/castblock-php.phar:14
app:run [-c|--category CATEGORY]`

**Comment by NGPriest** [comment]
Hoping this helps

>go-chromecast status --debug
>Found 6 cast dns entries, select one:
><deleted>
>Enter selection: 4
>using device name=<deleted> addr=<deleted> port=8009 uuid=<deleted>
>YouTube (PLAYING), title="<deleted>", artist="<deleted>", time remaining=53s/265s, volume=0.14, muted=false

**Comment by willemstuursma** [comment]
Thanks @NGPriest for the detailed report. Would it be possible to share which video you were playing? Then I'll debug with my own Chromecast as well. Pretty weird there is no video id in the output.

**Comment by willemstuursma** [comment]
In addition, could you share the version of `chromecast-go` that you are using?

**Comment by NGPriest** [comment]
> In addition, could you share the version of `chromecast-go` that you are using?

> go-chromecast --version
go-chromecast v0.2.12 (ad6b39b) 2022-03-11T07:28:18Z

**Comment by willemstuursma** [comment]
I'm sorry I was unable to reproduce the issue you were having with the output of `go-chromecast`. Did you edit the output before placing it here?

**Comment by NGPriest** [comment]
> I'm sorry I was unable to reproduce the issue you were having with the output of `go-chromecast`. Did you edit the output before placing it here?

Nope

**Comment by willemstuursma** [comment]
Thanks. I think it is a problem with `go-chromecast` then, you can try opening an issue there maybe. 

I'll make some patches to ensure that this application does not crash if this happens.
